services:
  blog-server:
    image: ghcr.io/skyone-wzw/blog-server:v1.0.1
    container_name: blog-server
    restart: unless-stopped
    volumes:
      - "./data:/data"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/data/data.db"
      DATA_DIR: "/data"
      SECRET_KEY: "changeme888888888888888888888888"
      SECRET_IV: "changeme88888888"
      AUTH_EMAIL: changeme@example.com
      AUTH_PASSWORD: changeme
