version: "3.8"

services:
  blog-server:
    image: blog-server:latest
    container_name: blog-server
    restart: unless-stopped
    volumes:
      - "./data:/app/data"
      - "./images:/app/images"
    networks:
      - proxy
    environment:
      DATABASE_URL: "file:/app/data/data.db"
      SECRET_KEY: "88888888888888888888888888888888"
      SECRET_IV: "8888888888888888"
      AUTH_EMAIL: abc@qq.com
      AUTH_PASSWORD: 233

networks:
  proxy:
    external: true
